[versions]
applovin = "13.1.0.0"
facebook = "6.18.0.0"
inmobi = "10.8.0.0"
ironsource = "8.6.1.0"
kotlin = "2.0.20"
agp = "8.1.0"
compileSdk = "34"
mintegral = "16.8.61.0"
pangle = "6.5.0.3.0"
targetSdk = "34"
minSdk = "21"
appcompat = "1.7.0"
gridlayout = "1.0.0"
material = "1.12.0"
constraintlayout = "2.1.4"
sdp-android = "1.1.1"
billing-ktx = "7.1.0"
lifecycle-extensions = "2.2.0"
lifecycle-runtime-ktx = "2.8.5"
junit = "4.13.2"
unity = "4.13.1.0"
unityAds = "4.13.1"
vungle = "7.4.2.0"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
applovin = { module = "com.google.ads.mediation:applovin", version.ref = "applovin" }
facebook = { module = "com.google.ads.mediation:facebook", version.ref = "facebook" }
gridlayout = { module = "androidx.gridlayout:gridlayout", version.ref = "gridlayout" }
inmobi = { module = "com.google.ads.mediation:inmobi", version.ref = "inmobi" }
ironsource = { module = "com.google.ads.mediation:ironsource", version.ref = "ironsource" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
mintegral = { module = "com.google.ads.mediation:mintegral", version.ref = "mintegral" }
pangle = { module = "com.google.ads.mediation:pangle", version.ref = "pangle" }
sdp-android = { module = "com.intuit.sdp:sdp-android", version.ref = "sdp-android" }
billing-ktx = { module = "com.android.billingclient:billing-ktx", version.ref = "billing-ktx" }
lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle-extensions" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
junit = { module = "junit:junit", version.ref = "junit" }
unity = { module = "com.google.ads.mediation:unity", version.ref = "unity" }
unity-ads = { module = "com.unity3d.ads:unity-ads", version.ref = "unityAds" }
vungle = { module = "com.google.ads.mediation:vungle", version.ref = "vungle" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }